/*
 * CrowdStrike API Specification
 *
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and more information about API endpoints that don't yet support OAuth2, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation). To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`. Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EntitiesOdsScheduleScanRequest {
    #[serde(rename = "cloud_ml_level_detection")]
    pub cloud_ml_level_detection: i32,
    #[serde(rename = "cloud_ml_level_prevention")]
    pub cloud_ml_level_prevention: i32,
    #[serde(rename = "cpu_priority")]
    pub cpu_priority: i32,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "endpoint_notification")]
    pub endpoint_notification: bool,
    #[serde(rename = "file_paths")]
    pub file_paths: Vec<String>,
    #[serde(rename = "host_groups")]
    pub host_groups: Vec<String>,
    #[serde(rename = "initiated_from")]
    pub initiated_from: String,
    #[serde(rename = "max_duration")]
    pub max_duration: i32,
    #[serde(rename = "max_file_size")]
    pub max_file_size: i32,
    #[serde(rename = "pause_duration")]
    pub pause_duration: i32,
    #[serde(rename = "quarantine")]
    pub quarantine: bool,
    #[serde(rename = "scan_exclusions")]
    pub scan_exclusions: Vec<String>,
    #[serde(rename = "schedule")]
    pub schedule: Box<crate::models::DomainSchedule>,
    #[serde(rename = "sensor_ml_level_detection")]
    pub sensor_ml_level_detection: i32,
    #[serde(rename = "sensor_ml_level_prevention")]
    pub sensor_ml_level_prevention: i32,
}

impl EntitiesOdsScheduleScanRequest {
    pub fn new(
        cloud_ml_level_detection: i32,
        cloud_ml_level_prevention: i32,
        cpu_priority: i32,
        description: String,
        endpoint_notification: bool,
        file_paths: Vec<String>,
        host_groups: Vec<String>,
        initiated_from: String,
        max_duration: i32,
        max_file_size: i32,
        pause_duration: i32,
        quarantine: bool,
        scan_exclusions: Vec<String>,
        schedule: crate::models::DomainSchedule,
        sensor_ml_level_detection: i32,
        sensor_ml_level_prevention: i32,
    ) -> EntitiesOdsScheduleScanRequest {
        EntitiesOdsScheduleScanRequest {
            cloud_ml_level_detection,
            cloud_ml_level_prevention,
            cpu_priority,
            description,
            endpoint_notification,
            file_paths,
            host_groups,
            initiated_from,
            max_duration,
            max_file_size,
            pause_duration,
            quarantine,
            scan_exclusions,
            schedule: Box::new(schedule),
            sensor_ml_level_detection,
            sensor_ml_level_prevention,
        }
    }
}
