/*
 * CrowdStrike API Specification
 *
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: 2025-09-19T00:00:03Z
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsMockExecutionCreateRequestV1 {
    #[serde(rename = "definition", skip_serializing_if = "Option::is_none")]
    pub definition: Option<Box<models::ModelsDefinitionCreateRequestV2>>,
    /// Mock activity data and trigger data for non-on-demand executions, keyed by node ID, may include trigger and/or activity nodes
    #[serde(rename = "mocks")]
    pub mocks: String,
    /// Trigger data for on-demand executions
    #[serde(rename = "on_demand_trigger", skip_serializing_if = "Option::is_none")]
    pub on_demand_trigger: Option<String>,
}

impl ModelsMockExecutionCreateRequestV1 {
    pub fn new(mocks: String) -> ModelsMockExecutionCreateRequestV1 {
        ModelsMockExecutionCreateRequestV1 {
            definition: None,
            mocks,
            on_demand_trigger: None,
        }
    }
}

