/*
 * CrowdStrike API Specification
 *
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: 2025-09-19T00:00:03Z
 * 
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsScanInfoType {
    #[serde(rename = "CorrelationUUID", skip_serializing_if = "Option::is_none")]
    pub correlation_uuid: Option<String>,
    #[serde(rename = "RequestedAt", skip_serializing_if = "Option::is_none")]
    pub requested_at: Option<String>,
    #[serde(rename = "ScanUUID", skip_serializing_if = "Option::is_none")]
    pub scan_uuid: Option<String>,
    #[serde(rename = "UserUUID", skip_serializing_if = "Option::is_none")]
    pub user_uuid: Option<String>,
    #[serde(rename = "Username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "cid", skip_serializing_if = "Option::is_none")]
    pub cid: Option<String>,
}

impl ModelsScanInfoType {
    pub fn new() -> ModelsScanInfoType {
        ModelsScanInfoType {
            correlation_uuid: None,
            requested_at: None,
            scan_uuid: None,
            user_uuid: None,
            username: None,
            cid: None,
        }
    }
}

