/*
 * CrowdStrike API Specification
 *
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestPeriodCloudAwsAccountCreateExtV1 {
    #[serde(rename = "account_id", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "account_type", skip_serializing_if = "Option::is_none")]
    pub account_type: Option<String>,
    #[serde(rename = "csp_events", skip_serializing_if = "Option::is_none")]
    pub csp_events: Option<bool>,
    #[serde(rename = "is_master", skip_serializing_if = "Option::is_none")]
    pub is_master: Option<bool>,
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    #[serde(rename = "products", skip_serializing_if = "Option::is_none")]
    pub products: Option<Vec<models::RestPeriodAccountProductUpsertRequestExtV1>>,
}

impl RestPeriodCloudAwsAccountCreateExtV1 {
    pub fn new(organization_id: String) -> RestPeriodCloudAwsAccountCreateExtV1 {
        RestPeriodCloudAwsAccountCreateExtV1 {
            account_id: None,
            account_type: None,
            csp_events: None,
            is_master: None,
            organization_id,
            products: None,
        }
    }
}
