name: Publish to crates.io
on:
  push:
    # Triggers when pushing tags in a certain format (e.g. 1.2.3)
    tags: ['[0-9]+.[0-9]+.[0-9]+']
permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: crates-io-publishing
    permissions:
      id-token: write
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
      with:
        egress-policy: audit

    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - uses: rust-lang/crates-io-auth-action@bbd81622f20ce9e2dd9622e3218b975523e45bbe # v1.0.4
      id: auth
    - run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
